---
# -----------------------------------------------------------------------------
# GitLab CI configuration for gitlab ci.
# -----------------------------------------------------------------------------
include:
  - local: _common.yml
