---
# -----------------------------------------------------------------------------
# This is the central CI/CD process for Ansible Playbooks.
# -----------------------------------------------------------------------------
default:
  tags:
    - process-ci

include:
  - local: _configs/_stages.yml
  - local: _configs/_workflow.yml
  ### prepare
  - local: _configs/prepare.yml
  ### validate
  - local: _rules/validate.yml
  - local: _configs/validate.yml
  - component: $CI_SERVER_FQDN/pl.rachuna-net/cicd/components/validate/ansible@$COMPONENT_VERSION_VALIDATE
    inputs:
      docker_image: $CONTAINER_IMAGE_ANSIBLE
      ansible_inventory: inventory/hosts.yml
  ### unit-test
  ### build
  ### sast
  - local: _configs/sast.yml
  ### release
  - local: _configs/release.yml
  ### deploy
  - local: _rules/deploy.yml
  - component: $CI_SERVER_FQDN/pl.rachuna-net/cicd/components/deploy/ansible@$COMPONENT_VERSION_DEPLOY
    inputs:
      docker_image: $CONTAINER_IMAGE_ANSIBLE
      ansible_inventory: inventory/hosts.yml

✅ ansible-playbook check:
  rules: !reference [.role:validate:ansible, rules]

💥 ansible playbook:
  rules: !reference [.rule:deploy:ansible, rules]
