---
# -----------------------------------------------------------------------------
# GitLab CI configuration for opentofu.
# -----------------------------------------------------------------------------
include:
  - local: _common.yml
  ### opentofu
  - component: $CI_SERVER_FQDN/pl.rachuna-net/cicd/components/infrastructure/opentofu@v1.0.0

### validate
🕵 opentofu fmt:
  needs:
    - job: 🔍 Input Parameters
    - job: 🔍 Analyze Conventional Commits
    - job: 🕵 Set Version

✅ opentofu validate:
  needs:
    - job: 🔍 Input Parameters
    - job: 🔍 Analyze Conventional Commits
    - job: 🕵 Set Version

✅ tflint:
  needs:
    - job: 🔍 Input Parameters
    - job: 🔍 Analyze Conventional Commits
    - job: 🕵 Set Version

✅ terraform-docs:
  rules:
    - when: never

### unit-test
🧪 opentofu plan:
  needs:
    - job: 🕵 YAML lint
      optional: true
    - job: 🕵 opentofu fmt
    - job: ✅ opentofu validate
    - job: ✅ tflint
  rules:
    - when: on_success

### release
📍 Publish Version:
  needs:
    - job: 🧪 opentofu plan

### deploy
💥 opentofu apply:
  needs:
    - job: 📍 Publish Version
  rules: !reference [.rule:deploy:opentofu, rules]
