---
# -----------------------------------------------------------------------------
# This is the central CI/CD process for Terraform.
# -----------------------------------------------------------------------------
default:
  tags:
    - process-ci

include:
  - local: _stages/_definitions.yml
  - local: _configs/_workflow.yml
  ### prepare
  - local: _stages/prepare.yml
  ### validate
  - local: _stages/validate.yml
  ### unit-test
  ### sast
  - local: _stages/sast.yml
  ### release
  - local: _stages/release.yml


🕵 Set Version:
  stage: prepare
  rules:
    - when: on_success


🔍 Input Parameters:
  stage: prepare
  rules:
    - when: on_success


🔍 Analyze Conventional Commits:
  stage: prepare
  rules:
    - when: on_success


🕵 YAML lint:
  stage: validate
  rules: !reference [.rule:validate:yamllint, rules]


✅ tflint:
  stage: validate
  rules: !reference [.rule:validate:terraform, rules]


✅ terraform-docs:
  stage: validate
  rules: !reference [.rule:validate:terraform, rules]


🕵 terraform fmt:
  stage: validate
  rules: !reference [.rule:validate:terraform, rules]


💪 sonarqube scanner:
  needs:
    - job: 🕵 Set Version
      artifacts: true
  variables:
    SONAR_PROJECT_KEY: $SONARQUBE_CLOUD_PROJECT_ID
    SONAR_PROJECT_VERSION: $RELEASE_CANDIDATE_VERSION
  rules:
    - if: $IS_ENABLED_SONARQUBE != "true"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_OPEN_MERGE_REQUESTS
      when: on_success


📍 Publish Version:
  stage: release
  rules:
    - when: on_success
