---
# -----------------------------------------------------------------------------
# This is the central CI/CD process for Terraform and Terraform modules.
# -----------------------------------------------------------------------------
default:
  tags:
    - process-ci

include:
  - local: _stages/_definitions.yml
  - local: _configs/_workflow.yml
  ### prepare
  - local: _stages/prepare.yml
  ### validate
  - local: _rules/validate.yml
  - local: _stages/validate.yml
  # - component: $CI_SERVER_FQDN/pl.rachuna-net/cicd/components/validate/terraform@$COMPONENT_VERSION_VALIDATE
  - component: $CI_SERVER_FQDN/pl.rachuna-net/cicd/components/validate/terraform@test/1
    inputs:
      docker_image: $CONTAINER_IMAGE_TERRAFORM
  ### unit-test
  - local: _rules/unit-test.yml
  - component: $CI_SERVER_FQDN/pl.rachuna-net/cicd/components/unit-test/terraform@$COMPONENT_VERSION_UNIT_TEST
    inputs:
      docker_image: $CONTAINER_IMAGE_TERRAFORM
  ### sast
  - local: _stages/sast.yml
  ### release
  - local: _stages/release.yml
  ### deploy
  - local: _rules/deploy.yml
  - component: $CI_SERVER_FQDN/pl.rachuna-net/cicd/components/deploy/terraform@$COMPONENT_VERSION_DEPLOY
    inputs:
      docker_image: $CONTAINER_IMAGE_TERRAFORM


✅ terraform validate:
  rules: !reference [.rule:validate:terraform, rules]


✅ tflint:
  rules: !reference [.rule:validate:terraform, rules]


🕵 terraform fmt:
  rules: !reference [.rule:validate:terraform, rules]


🧪 terraform plan:
  rules: !reference [.rule:unit-test:terraform, rules]


💥 terraform apply:
  needs:
    - job: 🧪 terraform plan
  rules: !reference [.rule:deploy:terraform, rules]
